apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-the-docs-forestry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: just-the-docs-forestry
  template:
    metadata:
      labels:
        app: just-the-docs-forestry
    spec:
      containers:
      - name: website
        image: europe-central2-docker.pkg/absolute-keel-345710/just-the-docs-forestry/just-the-docs-forestry:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: just-the-docs-forestry
spec:
  selector:
    app: just-the-docs-forestry
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer